In [1]:
import pandas as pd
import numpy as np
import random
import matplotlib.pyplot as plt
import csv
from pandas import Series
%matplotlib inline
path_to_data = '../data/'
train_data = pd.read_csv(path_to_data + 'training_data.csv')
test_data = pd.read_csv(path_to_data + 'test_data.csv')
print(train_data.shape)
print(test_data.shape)

(2797, 20)
(575, 20)


In [2]:
train_data_nafill = train_data.fillna('missing')
test_data_nafill = test_data.fillna('missing')

In [11]:
#Train CountVectorizer
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer()

#Train TfidfVectorizer
#from sklearn.feature_extraction.text import TfidfVectorizer
#vectorizer = TfidfVectorizer(sublinear_tf=True, max_df=0.5,stop_words='english')

#Train HashingVectorizer
#from sklearn.feature_extraction.text import HashingVectorizer
#vectorizer = HashingVectorizer(stop_words='english', non_negative=True)

X_train_status = vectorizer.fit_transform(train_data_nafill.status)
X_test_status = vectorizer.transform(test_data_nafill.status)
y_train = train_data_nafill.bot

from sklearn.linear_model import LogisticRegression
clf = LogisticRegression()
clf = clf.fit(X_train_status, y_train)
status_predicted = clf.predict(X_test_status)
status_predicted

array([0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0,
       0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1,
       0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1,
       1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1,
       1, 1,

In [4]:
X_train_desc = vectorizer.fit_transform(train_data_nafill.description)
X_test_desc = vectorizer.transform(test_data_nafill.description)

clf = LogisticRegression()
clf = clf.fit(X_train_desc, y_train)
desc_predicted = clf.predict(X_test_desc)
desc_predicted

array([0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0,
       1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0,
       1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1,
       0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1,
       1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1,
       1, 1,

In [40]:
#Train CountVectorizer
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer()

#Train TfidfVectorizer
#from sklearn.feature_extraction.text import TfidfVectorizer
#vectorizer = TfidfVectorizer(sublinear_tf=True, max_df=0.5,stop_words='english')

#Train HashingVectorizer
#from sklearn.feature_extraction.text import HashingVectorizer
#vectorizer = HashingVectorizer(stop_words='english', non_negative=True)

X_train_status = vectorizer.fit_transform(train_data_nafill.status)
X_test_status = vectorizer.transform(test_data_nafill.status)
y_train = train_data_nafill.bot

from sklearn.linear_model import LogisticRegression
clf = LogisticRegression()
clf = clf.fit(X_train_status, y_train)
status_predicted = clf.predict(X_test_status)

X_train_desc = vectorizer.fit_transform(train_data_nafill.description)
X_test_desc = vectorizer.transform(test_data_nafill.description)

clf = LogisticRegression()
clf = clf.fit(X_train_desc, y_train)
desc_predicted = clf.predict(X_test_desc)

n = test_data_nafill.shape[0]
uid = test_data.id.values
verified = test_data.verified.values
def_profile = test_data.default_profile.values
def_profile_img = test_data.default_profile_image.values
has_ext_profile = test_data.has_extended_profile.values
followers_count = test_data.followers_count.values
friends_count = test_data.friends_count.values
desc = test_data.description.values
listed_count = test_data.listed_count.values
favourites_count = test_data.favorites_count.values

predicted = status_predicted
for i in range(0,n):
    if followers_count[i] == 'None' or int(followers_count[i]) <= 8:
        predicted[i] = 1
        continue
    if friends_count[i] == 'None' or int(friends_count[i]) <= 6:
        predicted[i] = 1
        continue
    if followers_count[i] != 'None' and int(followers_count[i]) > 100000:
        predicted[i] = 0
        continue
    if str(desc[i]).lower().find('bot') > 0:
        predicted[i] = 1
        continue
    if str(desc[i]).lower().find('register') > 0:
        predicted[i] = 1
        continue
    if listed_count[i] != 'None' and int(listed_count[i]) > 3000:
        predicted[i] = 0
    if favourites_count[i] != 'None' and int(favourites_count[i]) >= 10000:
        predicted[i] = 0
    if desc_predicted[i] == 0 and predicted[i] == 1:
        predicted[i] = 0

f = open('result.csv','wb+')
f.write('Id,Bot\n')
for i in range(0,n):
    f.write('%d,%s\n' %(int(uid[i]), predicted[i]))
f.close
predicted

array([0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1,
       1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1,
       0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1,
       1, 1,